# Generated by Django 3.1.1 on 2020-09-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20200915_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default='hotelpic3.jpg', upload_to='food_pics'),
        ),
    ]
